subject:
    resource: "@SubjectBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

