homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

create_panier:
    path:     /panier
    defaults: { _controller: AppBundle:Default:createPanier }

show_panier:
    path:     /rappel
    defaults: { _controller: AppBundle:Default:showPanier }


