services:
#    subject.example:
#        class: SubjectBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'